name: Update CHANGELOG
on:
  workflow_dispatch:
  pull_request:
  push:

permissions: {}

jobs:
  update-changelog:
    uses: ./.github/workflows/reusable-update-changelog.yml
    permissions:
      contents: write
    with:
      birth_year: ${{ vars.MY_BIRTH_YEAR }}
      birth_month: ${{ vars.MY_BIRTH_MONTH }}
